PjaProjekt-war/src/java/src/controllers/CartController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.controllers;

import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import src.api.CartManage;
import src.models.Reservation;

/**
 *
 * @author fxdp
 */
@SessionScoped
@Named("cartCtl")
public class CartController implements Serializable {
    
    @EJB
    CartManage cartManage;
    
    public List<Reservation> getReservations(){
        
        
        return cartManage.getReservations();
    }
    
    public void addReservation(Reservation r){
        cartManage.addReservation(r);
    }
    
    public void deleteReservation(Reservation r){
        cartManage.removeReservation(r);
    }
    
    
    public String confirm(){
        
        return "add-user-data";
    }
    
    
    public String discard(){
        cartManage.discard();
        return "cart";
    }
    
    public void afterOrder(){
        cartManage.afterOrder();
        
    }
    
}

PjaProjekt-war/src/java/src/controllers/CategoryController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.controllers;

import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import src.api.CategoryManage;
import src.models.Category;

/**
 *
 * @author fxdp
 */
@ApplicationScoped
@Named("categoryCtl")
public class CategoryController {

    @EJB
    CategoryManage categoryManage;

    private String name;

    public String saveForm() {
        categoryManage.add(name);
        return "category_add";
    }
    
    public List<Category> getCategories(){
        return categoryManage.getCategories();
    
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}

PjaProjekt-war/src/java/src/controllers/ShowToolController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.controllers;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import src.api.ReservationManage;

import src.models.Tool;

/**
 *
 * @author fxdp
 */
@SessionScoped
@Named
public class ShowToolController implements Serializable {

    private Tool showTool;
    private Calendar sinceDate;
    private Calendar toDate;
    private String sinceDateString;
    private String toDateString;
    private int totalPrice = 0;
    private String actual = "";

    public int getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(int totalPrice) {
        this.totalPrice = totalPrice;
    }

    public String getActual() {
        return actual;
    }

    public void setActual(String actual) {
        this.actual = actual;
    }

    @EJB
    private ReservationManage resManage;

    @Inject
    CartController cartCtl;

    ShowToolController() {

    }

    public String show(Tool tool) throws ParseException {
        this.showTool = tool;
        /*
        this.sinceDate = resManage.getSinceDateByTool(tool);
        this.toDate = resManage.getToDateByTool(tool);
        
         */
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yy");

        this.sinceDateString = dateFormat.format(resManage.getSinceDateByTool(tool).getTime());
        this.toDateString = dateFormat.format(resManage.getToDateByTool(tool).getTime());
        if (resManage.getToDateByTool(tool).equals(new GregorianCalendar(2999, 0, 31))) {
            this.toDateString = "";
        }

        if (resManage.isRented(tool)) {
            this.actual = "Půjčeno";
        } else {
            this.actual = "Volné";
        }

        return "tool-detail";
    }

    public String submit() throws ParseException {
        /*
        long resId = resManage.add(this.sinceDate, this.toDate, this.showTool, this.totalPrice);
        cartCtl.addReservation(resManage.getById(resId));
        System.out.println("Velikost kosiku " + cartCtl.getReservations().size());
        this.sinceDate = resManage.getSinceDateByTool(this.showTool);
        this.toDate = resManage.getToDateByTool(this.showTool);
        if (resManage.isRented(this.showTool)) {
            this.actual = "Půjčeno";
        } else {
            this.actual = "Volné";
        }
         */
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yy");
        Calendar sinceDateTmp = Calendar.getInstance();
        sinceDateTmp.setTime(dateFormat.parse(this.sinceDateString));
        
        Calendar toDateTmp = Calendar.getInstance();
        toDateTmp.setTime(dateFormat.parse(this.toDateString));
        
        long resId = resManage.add(sinceDateTmp, toDateTmp, this.showTool, this.totalPrice);
        cartCtl.addReservation(resManage.getById(resId));
        this.sinceDateString = dateFormat.format(resManage.getSinceDateByTool(this.showTool).getTime());
        this.toDateString = dateFormat.format(resManage.getToDateByTool(this.showTool).getTime());
        if (resManage.getToDateByTool(this.showTool).equals(new GregorianCalendar(2999, 0, 31))) {
            this.toDateString = "";
        }
        
        if (resManage.isRented(this.showTool)) {
            this.actual = "Půjčeno";
        } else {
            this.actual = "Volné";
        }
        
        return "tool-detail";

    }

    public Tool getShowTool() {
        return showTool;
    }

    public void setShowTool(Tool showTool) {
        this.showTool = showTool;
    }

    public String getSinceDateInString() {
        /*
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yy");
        dateFormat.setTimeZone(sinceDate.getTimeZone());
        return dateFormat.format(sinceDate.getTime());
         */
        return this.sinceDateString;

    }

    public String getToDateInString() {
        /*
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yy");
        if (toDate.equals(new GregorianCalendar(2999, 0, 31))) {
            return "";
        }
        dateFormat.setTimeZone(toDate.getTimeZone());
        return dateFormat.format(toDate.getTime());
         */

        return this.toDateString;

    }

    public void setSinceDateInString(String sinceDate) throws ParseException {
        /*
        if (sinceDate == null) {

        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy", Locale.US);

            this.sinceDate.setTime(dateFormat.parse(sinceDate));

        }
         */
        if (sinceDate == null) {

        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy", Locale.US);
            Calendar cal = Calendar.getInstance();
            cal.setTime(dateFormat.parse(sinceDate));
            dateFormat = new SimpleDateFormat("dd.MM.yy");
            this.sinceDateString = dateFormat.format(cal.getTime());

        }
    }

    public void setToDateInString(String toDate) throws ParseException {
        /*
        if (toDate == null) {

        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy", Locale.US);

            this.toDate.setTime(dateFormat.parse(toDate));

        }
         */

        if (toDate == null) {

        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy", Locale.US);
            Calendar cal = Calendar.getInstance();
            cal.setTime(dateFormat.parse(toDate));
            dateFormat = new SimpleDateFormat("dd.MM.yy");
            this.toDateString = dateFormat.format(cal.getTime());

        }

    }

    public String getTotalPriceInString() throws ParseException {
        /*     
        if (toDate.equals(new GregorianCalendar(2999, 0, 31))) {
            return "";
        } else {
            long end = this.toDate.getTimeInMillis();
            long start = this.sinceDate.getTimeInMillis();
            long total = TimeUnit.MILLISECONDS.toDays(Math.abs(end - start));
            this.totalPrice = (int) (total * this.showTool.getPriceForDay());
            return String.valueOf(total * this.showTool.getPriceForDay()) + " CZK";
        }
         */

        if (this.toDateString.equals("")) {
            return "";
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yy");
            Calendar cal = Calendar.getInstance();
            cal.setTime(dateFormat.parse(this.sinceDateString));
            Calendar cal1 = Calendar.getInstance();
            cal1.setTime(dateFormat.parse(this.toDateString));

            long end = cal1.getTimeInMillis();
            long start = cal.getTimeInMillis();
            long total = TimeUnit.MILLISECONDS.toDays(Math.abs(end - start));
            this.totalPrice = (int) (total * this.showTool.getPriceForDay());
            return String.valueOf(total * this.showTool.getPriceForDay()) + " CZK";
        }

    }

    public Calendar getSinceDate() {
        return sinceDate;
    }

    public void setSinceDate(Calendar sinceDate) {
        this.sinceDate = sinceDate;
    }

    public Calendar getToDate() {
        return toDate;
    }

    public void setToDate(Calendar toDate) {
        this.toDate = toDate;
    }

}

PjaProjekt-war/src/java/src/controllers/ToolListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.controllers;

import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import javax.inject.Named;
import src.api.CategoryManage;
import src.api.ToolManage;
import src.models.Tool;
import src.models.Category;

/**
 *
 * @author fxdp
 */
@ApplicationScoped
@Named("toolListCtl")
public class ToolListController {

    @EJB
    private ToolManage toolManage;
    
    @EJB
    private CategoryManage catManage;

    private long catId = 0;

    public String showAll() {
        System.out.println("showAll");
        this.catId = 0;
        System.out.println(catId);
        return "tool-list.xhtml";
    }

    public String showByCategory(Category cat) {
            catId = cat.getId();
        return "tool-list.xhtml";
    }

    public List<Tool> getTools() {
        System.out.println("Vracim toolu:" + catId);
        if (catId == 0) {
            return toolManage.getTools();
        } else {
            return toolManage.getToolsByCategory(catManage.getById(catId));
        }

    }

}

PjaProjekt-war/src/java/src/controllers/ToolManageController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.controllers;

import java.io.DataInputStream;
import java.io.IOException;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.servlet.http.Part;
import src.api.CategoryManage;
import src.api.ToolManage;
import src.models.Tool;

/**
 *
 * @author fxdp
 */
@RequestScoped
@Named("toolManageCtl")
public class ToolManageController {

    @EJB
    private ToolManage toolManage;

    @EJB
    private CategoryManage catManage;
    private String name;
    private String info;
    private byte[] image = new byte[100];
    private int priceForDay;
    private Part uploadedFile;
    private long categoryId;

    public String saveForm() throws IOException {

        image = new byte[(int) uploadedFile.getSize()];
        DataInputStream dataIs = new DataInputStream(uploadedFile.getInputStream());
        dataIs.readFully(image);

        toolManage.add(name, info, image, catManage.getById(categoryId), priceForDay);
        return "tool-manage";
    }

    public List<Tool> getTools() {
        return toolManage.getTools();

    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public int getPriceForDay() {
        return priceForDay;
    }

    public void setPriceForDay(int priceForDay) {
        this.priceForDay = priceForDay;
    }

    public Part getUploadedFile() {
        return uploadedFile;
    }

    public void setUploadedFile(Part uploadedFile) {
        this.uploadedFile = uploadedFile;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
}

PjaProjekt-war/web/add-user-data.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:of="http://omnifaces.org/functions"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ez="http://xmlns.jcp.org/jsf/composite/ezcomp">


    <body>

        <ui:composition template="./templates/masterTemplate.xhtml">
            <ui:define name="top">
                <ui:include src="./templates/commonHeader.xhtml "/>
            </ui:define>
            <ui:define name="left">
                <ui:include src="templates/commonMenu.xhtml" />
            </ui:define>

            <ui:define name="content">
                <h:form id="form">


                    <h:panelGrid columns="2" cellpadding="5">
                        <p:outputLabel for="firstName">Jméno:</p:outputLabel>
                        <p:inputText id="firstName" value="#{orderCtl.firstName}"></p:inputText>

                        <p:outputLabel for="secondName">Příjmení:</p:outputLabel>
                        <p:inputText id="secondName" value="#{orderCtl.secondName}"></p:inputText>

                        <p:outputLabel for="tel">Tel:</p:outputLabel>
                        <p:inputText id="tel" value="#{orderCtl.telNumber}"></p:inputText>

                        <p:outputLabel for="mail">Email:</p:outputLabel>
                        <p:inputText id="mail" value="#{orderCtl.email}"></p:inputText>          
                    </h:panelGrid>
                    <p:commandButton  ajax="false" value="Dokončit objednávku" 
                                      action="#{orderCtl.submit()}"
                                      actionListener="#{dfView.showMessageAfterOrder()}"
                                      icon="ui-icon-check"/>







                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

PjaProjekt-war/web/cart.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:of="http://omnifaces.org/functions"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ez="http://xmlns.jcp.org/jsf/composite/ezcomp">


    <body>

        <ui:composition template="./templates/masterTemplate.xhtml">
            <ui:define name="top">
                <ui:include src="./templates/commonHeader.xhtml "/>
            </ui:define>

            <ui:define name="left">
                <ui:include src="templates/commonMenu.xhtml" />
            </ui:define>

            <ui:define name="content">
                <h:form enctype="multipart/form-data">
                    <h2>Košík</h2>

                    <ui:repeat value="#{cartCtl.reservations}" var="r">


                        <!--
                        <h:panelGroup layout="block" id="mainDiv" >
                            <h:outputLabel for="what">What:</h:outputLabel>
                            <h:outputText id="what" value="#{r.tool.name}"></h:outputText>
                            <br></br>
                            <h:outputLabel for="since">Since:</h:outputLabel>
                            <h:outputText id="since" value="#{r.sinceDateInString}"></h:outputText>
                            <br></br>
                            <h:outputLabel for="to">To:</h:outputLabel>
                            <h:outputText id="to" value="#{r.toDateInString}"></h:outputText>                 
                            <br></br>
                            <h:outputLabel for="total">PriceTotal:</h:outputLabel>
                            <h:outputText id="total" value="#{r.priceTotal}"></h:outputText> 

                        </h:panelGroup>
                        -->
                        <p:panelGrid columns="2">
                            <h:outputLabel for="what">Název přístroje:</h:outputLabel>
                            <h:outputText id="what" value="#{r.tool.name}"></h:outputText> 

                            <h:outputLabel for="since">Výpůjčka od:</h:outputLabel>
                            <h:outputText id="since" value="#{r.sinceDateInString}"></h:outputText>

                            <h:outputLabel for="to">Výpůjčka do:</h:outputLabel>
                            <h:outputText id="to" value="#{r.toDateInString}"></h:outputText>

                            <h:outputLabel for="total">Celková cena:</h:outputLabel>
                            <h:outputText id="total" value="#{r.priceTotal} CZK"></h:outputText> 
                        </p:panelGrid>                        
                    </ui:repeat>
                    <h:panelGrid columns="2" cellpadding="5">
                        <c:if test="#{not empty cartCtl.reservations}">
                            <p:commandButton ajax="false" value="Potvrdit objednávku" action="#{cartCtl.confirm()}" icon="ui-icon-check"/>
                            <p:commandButton ajax="false" value="Vyprázdnit košík" action="#{cartCtl.discard()}" icon="ui-icon-closethick"/>
                        </c:if>
                        <c:if test="#{empty cartCtl.reservations}">
                            <h3>Je prázdný</h3>
                        </c:if>


                    </h:panelGrid>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

PjaProjekt-war/web/tool-detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <body>

        <ui:composition template="./templates/masterTemplate.xhtml">
            <ui:define name="top">
                <ui:include src="./templates/commonHeader.xhtml "/>
            </ui:define>
            <ui:define name="left">
                <ui:include src="templates/commonMenu.xhtml" />
            </ui:define>

            <ui:define name="content">
                <h:form id="form">
                    <p:growl id="msgs" showDetail="true" />
                    <o:graphicImage value="#{imageController.get(showToolController.showTool.id)}" height="200px" width="200px"></o:graphicImage>
                    <br></br>


                    <h:panelGrid columns="2" cellpadding="5">

                        <h:outputLabel for="actual">Stav: </h:outputLabel>
                        <h:outputText id="actual" value="#{showToolController.actual}"></h:outputText>

                        <p:outputLabel for="name">Název:</p:outputLabel>
                        <h:outputText id="name" value="#{showToolController.showTool.name}"></h:outputText>

                        <h:outputLabel for="info">Informace:</h:outputLabel>
                        <h:outputText id="info" value="#{showToolController.showTool.info}"></h:outputText>

                        <h:outputLabel for="price">Cena výpůjčky/den:</h:outputLabel>
                        <h:outputText id="price" value="#{showToolController.showTool.priceForDay} CZK  "></h:outputText>




                        <p:outputLabel for="buttonSince" value="Vypůjčit od:" />
                        <p:calendar id="buttonSince"
                                    value="#{showToolController.sinceDateInString}"
                                    showOn="button"
                                    
                                    pattern="dd.MM.yy" mask="true"
                                    binding="#{date1}">
                            <p:ajax event="dateSelect" update="priceSum"/>
                            <p:ajax event="change" update="priceSum"/>
                        </p:calendar>

                        <p:outputLabel for="buttonTo" value="Vypůjčit do:" />
                        <p:calendar id="buttonTo" 
                                    value="#{showToolController.toDateInString}" 
                                    showOn="button"
                                    pattern="dd.MM.yy" mask="true"
                                    >

                            <p:ajax event="dateSelect" update="priceSum"/>
                            <p:ajax event="change" update="priceSum"/>
                             <!--  
                            <f:attribute name="startDate" value="#{showToolController.sinceDateInString}" />
                            <f:attribute name="showTool" value="#{showToolController.showTool}" />
                            
                            -->
                                
                            
                            
                            <f:attribute name="startDate" value="#{showToolController.sinceDateInString}" />                            
                            <f:attribute name="showTool" value="#{showToolController.showTool}"/> 
                            <f:validator validatorId="bfResValidator"></f:validator> 
                            <f:validator validatorId="secondDateValidator"></f:validator>
                        </p:calendar>



                        <h:outputLabel for="priceSum">Cena celkem:</h:outputLabel>
                        <h:outputText id="priceSum" value="#{showToolController.totalPriceInString}"></h:outputText>


                    </h:panelGrid>
                    <h:message for="buttonTo" style="color:red;"/>


                    <p:commandButton  ajax="false" value="Vložit do košíku"
                                      action="#{showToolController.submit()}"
                                      icon="ui-icon-check"
                                      actionListener="#{dfView.showMessageAfterConfirm()}">             

                    </p:commandButton>
                    <p:commandButton  ajax="false" value="Zobrazit rezervace" action="#{scheduleCtl.show(showToolController.showTool)}" icon="ui-icon-search"/>





                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

PjaProjekt-war/web/tool-list.xhtml
?<xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:of="http://omnifaces.org/functions"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:ez="http://xmlns.jcp.org/jsf/composite/ezcomp">


    <body>

        <ui:composition template="./templates/masterTemplate.xhtml">
            <ui:define name="top">
                <ui:include src="./templates/commonHeader.xhtml "/>
            </ui:define>
            <ui:define name="left">
                <ui:include src="templates/commonMenu.xhtml" />
            </ui:define>

            <ui:define name="content">
                <h:form enctype="multipart/form-data">


                    
                    <ui:repeat value="#{toolListCtl.tools}" var="t">
                        <h:commandLink action="#{showToolController.show(t)}" class="toolWrap">
                            <p:panelGrid columns="1">
                                <f:facet name="header">
                                    <o:graphicImage value="#{imageController.get(t.id)}" height="200px" width="200px"></o:graphicImage>
                                </f:facet>
                                <h:outputText id="name" value="#{t.name}"></h:outputText> 
                            </p:panelGrid>                                
                        </h:commandLink>
                    </ui:repeat>
                    
                    
                   




                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

PjaProjekt-war/web/tool-manage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:o="http://omnifaces.org/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


    <body>

        <ui:composition template="./templates/masterTemplate.xhtml">
            <ui:define name="top">
                <ui:include src="./templates/commonHeader.xhtml "/>
            </ui:define>
            <ui:define name="left">
                <ui:include src="templates/commonMenu.xhtml" />
            </ui:define>

            <ui:define name="content">
                <h:form enctype="multipart/form-data">



                    <h:panelGrid columns="2">
                        <h:outputLabel for="name">Název přístroje</h:outputLabel>
                        <h:inputText id="name" value="#{toolManageCtl.name}"></h:inputText>
                        
                        <h:outputLabel for="info">Info o přístroji</h:outputLabel>
                        <h:inputText id="info" value="#{toolManageCtl.info}"></h:inputText>
                        
                        <h:outputLabel for="fileAdd">Obrázek</h:outputLabel>
                        <h:inputFile id="fileAdd" value="#{toolManageCtl.uploadedFile}"></h:inputFile>
                        
                        <h:outputLabel for="category">Vybrat kategorii</h:outputLabel>
                        <h:selectOneMenu id="category" value="#{toolManageCtl.categoryId}">
                            <f:selectItems value="#{categoryCtl.categories}" var="c" itemLabel="#{c.name}" itemValue="#{c.id}" />
                        </h:selectOneMenu>
                        
                        
                        
                        <h:outputLabel for="priceAdd">Cena za den"</h:outputLabel>
                        <h:inputText id="priceAdd" value="#{toolManageCtl.priceForDay}"></h:inputText>

                    </h:panelGrid>   
                    <p:commandButton  ajax="false" value="Vložit vybavení" action="#{toolManageCtl.saveForm()}" icon="ui-icon-check"/>
                    
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>